/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managingrestaurant;

import Entities.itemPedido;
import Entities.mesa;
import Entities.pedido;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pmotel
 */
public class JFramePedido extends javax.swing.JFrame {

    private final JFrameRestaurante mainJFrameRestaurante;
    private mesa mesa;
    private JButton btnMesa;

    /**
     * Creates new form JFramePedido
     *
     * @param mainJFrameRestaurante
     * @param pedidoMesa
     * @param btnMesa
     */
    public JFramePedido(JFrameRestaurante mainJFrameRestaurante, mesa pedidoMesa, JButton btnMesa) {
        initComponents();
        this.mainJFrameRestaurante = mainJFrameRestaurante;
        this.mesa = pedidoMesa;
        this.btnMesa = btnMesa;
        fillJComboBox();
    }

    private JFramePedido() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void SetReserva(String clienteReserva) {
        jTextFieldClienteReserva.setVisible(false);
        jButtonReservar.setVisible(false);
        jLabelClienteReserva.setText(clienteReserva);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelClienteReserva = new javax.swing.JLabel();
        jTextFieldClienteReserva = new javax.swing.JTextField();
        jButtonReservar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonPedir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 340));

        jLabelClienteReserva.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelClienteReserva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClienteReserva.setText("jLabel1");

        jTextFieldClienteReserva.setText("jTextField1");

        jButtonReservar.setText("Reservar");
        jButtonReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Valor"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonPedir.setText("Pedir");
        jButtonPedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPedirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelClienteReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldClienteReserva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonReservar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPedir, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldClienteReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReservar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClienteReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPedir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservarActionPerformed
        jLabelClienteReserva.setText(jTextFieldClienteReserva.getText());
         btnMesa.setBackground(Color.YELLOW);
        if (!mainJFrameRestaurante.statusMesa(mesa.getNumero())) {
            mesa reservarMesa = new mesa(mesa.getNumero(), jTextFieldClienteReserva.getText(),new pedido(8));
            mainJFrameRestaurante.listaDeMesas.add(reservarMesa);
        }
    }//GEN-LAST:event_jButtonReservarActionPerformed

    private void jButtonPedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPedirActionPerformed
        String[] item = ((String)jComboBox1.getSelectedItem()).split("-");

        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        Object[] rowData = new Object[2];
        rowData[0] = item[0];
        rowData[1] = item[1];

        tableModel.addRow(rowData);
     
        // aqui esta sendo alimentado o array de itens do pedido
        // agora é tratar para que os itens sejam mostrados
        // no momento que o usuario clicar no botão da mesa
        // tenta continuar daqui e qualquer coisa só falar
        itemPedido novoItem;
        novoItem = new itemPedido(item[0],Double.parseDouble(item[1]));

        mesa.pedido.addItem(novoItem);
    }//GEN-LAST:event_jButtonPedirActionPerformed

    public void fillJComboBox() {

        jComboBox1.removeAllItems();
        jComboBox1.addItem("Frango frito - 12.90");
        jComboBox1.addItem("Frango assado - 18.90");
       
      
        
    }

    /**
     * "
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPedir;
    private javax.swing.JButton jButtonReservar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelClienteReserva;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldClienteReserva;
    // End of variables declaration//GEN-END:variables
}
